spring.application.name=social-content-manager
spring.profiles.active=production
server.port=8081
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
sscm.publishing.provider=LOCAL
sscm.publishing.scheduling.enabled=true
sscm.publishing.scheduling.fixed-delay-ms=60000
sscm.publishing.scheduling.initial-delay-ms=30000
sscm.publishing.scheduling.batch-size=25
